name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual or API-triggered runs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies (jq, Vercel CLI)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          npm install -g vercel

      - name: Create Vercel Project if Not Exists
        id: create_project
        run: |
          PROJECT_NAME="myvercelprojectnew"
          RESPONSE=$(curl -s -X POST "https://api.vercel.com/v9/projects" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
              "name": "'"$PROJECT_NAME"'",
              "framework": "other",
              "buildCommand": "pip install -r requirements.txt",
              "rootDirectory": "api",
              "installCommand": "pip install -r requirements.txt"
          }')

          PROJECT_ID=$(echo $RESPONSE | jq -r '.id')

          if [ "$PROJECT_ID" == "null" ]; then
            echo "❌ Project creation failed. Trying to fetch existing project..."
            RESPONSE=$(curl -s -X GET "https://api.vercel.com/v9/projects" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json")

            PROJECT_ID=$(echo $RESPONSE | jq -r ".projects[] | select(.name==\"$PROJECT_NAME\") | .id")
          fi

          if [ "$PROJECT_ID" == "null" ]; then
            echo "❌ Failed to create or retrieve project ID."
            exit 1
          fi

          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
          echo "✅ Vercel Project ID: $PROJECT_ID"

      - name: Connect GitHub Repository to Vercel
        run: |
          curl -X PATCH "https://api.vercel.com/v9/projects/$PROJECT_ID/git/connect" \
               -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"gitRepository": {"type": "github", "repo": "Test_Script", "org": "TimmyTobby"}}'

      - name: Deploy to Vercel
        run: vercel --prod --yes --name myvercelprojectnew --token ${{ secrets.VERCEL_TOKEN }} 
